INFO: 2018-08-21 10:30:27,611:DartRunner.py:108: Logfile is /root/Dart/log/DartRunner-2018-08-21-103027.log
INFO: 2018-08-21 10:30:27,611:DartRunner.py:109: Current Process Id: 35499
INFO: 2018-08-21 10:30:27,612:DartRunner.py:170: clusterList = dartexe 
INFO: 2018-08-21 10:30:27,612:DartRunner.py:178: dartexe
INFO: 2018-08-21 10:30:28,798:DartRunner.py:2008: NAME      READY     STATUS    RESTARTS   AGE
consul    1/1       Running   0          4d

INFO: 2018-08-21 10:30:28,912:DartRunner.py:2037: consul
INFO: 2018-08-21 10:30:28,912:DartRunner.py:2077: []
INFO: 2018-08-21 10:30:28,912:DartRunner.py:2078: []
INFO: 2018-08-21 10:30:28,912:DartRunner.py:247: /root/Dart/testset/OneTest.tst
INFO: 2018-08-21 10:30:28,913:DartRunner.py:258: Scanning File: /root/Dart/testset/OneTest.tst 
INFO: 2018-08-21 10:30:28,913:DartRunner.py:273: Reading tempRunFile : /tmp/OneTest.tst
INFO: 2018-08-21 10:30:29,148:DartRunner.py:2154: Ping on cluster dartexe Successful!
INFO: 2018-08-21 10:30:29,303:DartRunner.py:523: Dart DashBoard URL: http://dartdashboard.labs.teradata.com/report?run_id=180821-38
INFO: 2018-08-21 10:30:29,317:DartRunner.py:1696: Done inserting the information of run 180821-38
INFO: 2018-08-21 10:30:29,330:DartRunner.py:2665: DB Insert Success: NullTest
INFO: 2018-08-21 10:30:30,832:DartRunner.py:754: Looping the Main Loop: 1
INFO: 2018-08-21 10:30:30,935:DartRunner.py:1916: Running CheckHealth on cluster dartexe
INFO: 2018-08-21 10:30:32,936:DartRunner.py:941: Running Setup for the TestSet
INFO: 2018-08-21 10:30:32,937:DartRunner.py:964: {'dartexe': 'busy'}
INFO: 2018-08-21 10:30:32,937:DartRunner.py:965: {'dartexe': u'NullTest'}
INFO: 2018-08-21 10:30:32,937:DartRunner.py:975: 
Running Test: NullTest on Cluster: dartexe Thread Count: 1  

INFO: 2018-08-21 10:30:32,939:DartRunner.py:1130: Tests may be currently running..Sleeping for 10 seconds before checking the Queue!
INFO: 2018-08-21 10:30:32,939:DartRunner.py:1131: {'dartexe': 'busy'}
INFO: 2018-08-21 10:30:32,952:DartRunner.py:2555: Updated cluster: dartexe for test NullTest
ERROR: 2018-08-21 10:30:32,953:DartRunner.py:2918: Unable to run the command cat /home/beehive/bin/.build | grep 'BUILD_VERSION'
ERROR: 2018-08-21 10:30:32,953:DartRunner.py:2919: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac136b90>)
ERROR: 2018-08-21 10:30:32,954:DartRunner.py:2920: Traceback (most recent call last):
  File "DartRunner.py", line 2908, in runCommandOnQueen
    queenNode = queenNodes[0]
IndexError: list index out of range

ERROR: 2018-08-21 10:30:32,954:DartRunner.py:2918: Unable to run the command hadoop version
ERROR: 2018-08-21 10:30:32,955:DartRunner.py:2919: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac136b90>)
ERROR: 2018-08-21 10:30:32,955:DartRunner.py:2920: Traceback (most recent call last):
  File "DartRunner.py", line 2908, in runCommandOnQueen
    queenNode = queenNodes[0]
IndexError: list index out of range

INFO: 2018-08-21 10:30:32,955:DartRunner.py:2873: getHadoopVersion stdout = None
INFO: 2018-08-21 10:30:32,955:DartRunner.py:2874: getHadoopVersion stderr = None
INFO: 2018-08-21 10:30:32,955:DartRunner.py:2875: getHadoopVersion status = 1
INFO: 2018-08-21 10:30:32,955:DartRunner.py:2884: hdversion = None
INFO: 2018-08-21 10:30:32,956:DartRunner.py:2846: The cluster is without Hadoop, change db_version to Aster
INFO: 2018-08-21 10:30:32,967:DartRunner.py:2587: Updated Status: On test NullTest
INFO: 2018-08-21 10:30:32,967:DartRunner.py:2588: {'db_version': 'Aster', 'db_type': 'Classic', 'build_info': ''}
INFO: 2018-08-21 10:30:32,968:DartRunner.py:2214: Updating the status to Running in the database: NullTest!
INFO: 2018-08-21 10:30:32,978:DartRunner.py:2587: Updated Status: On test NullTest
INFO: 2018-08-21 10:30:32,978:DartRunner.py:2588: {'status': 'RUNNING', 'start_time': '2018-08-21 10:30:32'}
INFO: 2018-08-21 10:30:32,979:Dart.py:120: Logfile is /root/Dart/log/Dart-NullTest-180821-38-103032.log
INFO: 2018-08-21 10:30:33,602:Dart.py:390: NAME      READY     STATUS    RESTARTS   AGE
consul    1/1       Running   0          4d

INFO: 2018-08-21 10:30:33,602:Dart.py:418: consul
INFO: 2018-08-21 10:30:33,603:Dart.py:460: []
INFO: 2018-08-21 10:30:33,603:Dart.py:461: []
INFO: 2018-08-21 10:30:33,603:Dart.py:299: Test Set: SqlTests 
INFO: 2018-08-21 10:30:33,603:Dart.py:313: Running Testset: SqlTests
INFO: 2018-08-21 10:30:33,603:Dart.py:319:         Running Test: NullTest on Cluster dartexe
INFO: 2018-08-21 10:30:33,604:Dart.py:322: [u'NullTest', {u'OWNER': u'divya.sivanandan', 'testSet': u'SqlTests', 'testPlan': None, 'tester': 'root', 'projectName': 'MLEngine', 'buildNumber': '', 'buildName': 'beehive-ci-pipeline-main', u'USER': u'beehive', u'TIMEOUT': 800, u'PASSWORD': u'beehive', 'id': 1526706, u'CATEGORY': u'positive', u'EXPECTEDOUT': u'testsrc/queen/sql/test_sql/expectedQueryResults/null.out', u'NAME': u'NullTest', 'timeScale': 1, u'DATABASE': u'beehive', 'reTryCnt': 0, u'COMPONENT': u'queen/sql/test_sql', u'PRIORITY': u'2', 'runId': u'180821-38', u'TEMPLATE': u'True', u'ACTPARAMS': u'-a', 'release': 'GGR3', u'QUERY': u'testsrc/queen/sql/test_sql/input/null.sql', 'branchName': '8.00engine.ggr3', u'TYPE': u'SQL', 'testId': 1}, 0]
INFO: 2018-08-21 10:30:33,617:Dart.py:752: --------------------------------------------------
INFO: 2018-08-21 10:30:33,617:TestBase.py:42:           Using the following Test Parameters:
INFO: 2018-08-21 10:30:33,618:TestBase.py:43: --------------------------------------------------
INFO: 2018-08-21 10:30:33,618:TestBase.py:45:           OWNER : divya.sivanandan 
INFO: 2018-08-21 10:30:33,618:TestBase.py:45:           testSet : SqlTests 
INFO: 2018-08-21 10:30:33,618:TestBase.py:45:           testPlan : None 
INFO: 2018-08-21 10:30:33,618:TestBase.py:45:           tester : root 
INFO: 2018-08-21 10:30:33,618:TestBase.py:45:           projectName : MLEngine 
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           logPath : /root/Dart 
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           buildNumber :  
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           buildName : beehive-ci-pipeline-main 
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           USER : beehive 
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           TIMEOUT : 800 
INFO: 2018-08-21 10:30:33,619:TestBase.py:45:           filePath : queen/sql/test_sql 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           PASSWORD : beehive 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           id : 1526706 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           CATEGORY : positive 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           EXPECTEDOUT : testsrc/queen/sql/test_sql/expectedQueryResults/null.out 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           NAME : NullTest 
INFO: 2018-08-21 10:30:33,620:TestBase.py:45:           timeScale : 1 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           DATABASE : beehive 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           reTryCnt : 0 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           COMPONENT : queen/sql/test_sql 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           PRIORITY : 2 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           logTimestamp : 2018-08-21-103033 
INFO: 2018-08-21 10:30:33,621:TestBase.py:45:           runId : 180821-38 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           TEMPLATE : True 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           ACTPARAMS : -a 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           release : GGR3 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           QUERY : testsrc/queen/sql/test_sql/input/null.sql 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           branchName : 8.00engine.ggr3 
INFO: 2018-08-21 10:30:33,622:TestBase.py:45:           TYPE : SQL 
INFO: 2018-08-21 10:30:33,623:TestBase.py:45:           testId : 1 
INFO: 2018-08-21 10:30:33,623:TestBase.py:46: --------------------------------------------------
INFO: 2018-08-21 10:30:33,636:Kubernetes.py:82: Executing command [10.25.80.32]: kubectl get pods --namespace=cloud-aster
INFO: 2018-08-21 10:30:34,179:TestBase.py:170: NAME      READY     STATUS    RESTARTS   AGE
consul    1/1       Running   0          4d

INFO: 2018-08-21 10:30:34,180:Kubernetes.py:82: Executing command [10.25.80.32]: kubectl get svc queenexec-service -o json jsonpath={.spec.Ports} -n cloud-aster
ERROR: 2018-08-21 10:30:34,556:Dart.py:772: list index out of range
ERROR: 2018-08-21 10:30:34,556:Dart.py:773: The test raised an Unexpected Exception!
ERROR: 2018-08-21 10:30:34,556:Dart.py:774: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac06bea8>)
ERROR: 2018-08-21 10:30:34,571:Dart.py:775: Traceback (most recent call last):
  File "/root/Dart/Dart.py", line 758, in runTest
    result = testInstance.run()
  File "/root/Dart/lib/SqlRun.py", line 61, in run
    actParams, diffParams)
  File "/root/Dart/lib/TestBase.py", line 545, in excSqlFileAndCompareOutput
    queenNode = self.queenNames[0]
IndexError: list index out of range

INFO: 2018-08-21 10:30:34,572:Dart.py:781: The test NullTest has FAILED
ERROR: 2018-08-21 10:30:34,572:Dart.py:325: list index out of range
ERROR: 2018-08-21 10:30:34,572:Dart.py:327: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac038fc8>)
ERROR: 2018-08-21 10:30:34,572:Dart.py:328: Traceback (most recent call last):
  File "/root/Dart/Dart.py", line 323, in __init__
    self.runTest(testset, test[0], test[1], test[2])
  File "/root/Dart/Dart.py", line 758, in runTest
    result = testInstance.run()
  File "/root/Dart/lib/SqlRun.py", line 61, in run
    actParams, diffParams)
  File "/root/Dart/lib/TestBase.py", line 545, in excSqlFileAndCompareOutput
    queenNode = self.queenNames[0]
IndexError: list index out of range

INFO: 2018-08-21 10:30:34,573:Dart.py:329: Continuing with the remaining tests!
INFO: 2018-08-21 10:30:34,573:Dart.py:334: Test Set : SqlTests Total Execution Time: 0 
INFO: 2018-08-21 10:30:34,584:DartRunner.py:2587: Updated Status: On test NullTest
INFO: 2018-08-21 10:30:34,584:DartRunner.py:2588: {'status': 'FAIL', 'execution_time': '00:00:00', 'log_location': u'/root/DartLogs/dart-main-sls12-05_NullTest_2018-08-21-103033.log', 'end_time': '2018-08-21 10:30:34'}
INFO: 2018-08-21 10:30:34,916:DartRunner.py:2647: Successfully uploaded the Dart Test Log: dart-main-sls12-05_NullTest_2018-08-21-103033.log
INFO: 2018-08-21 10:30:34,924:DartDBConnect.py:127: Running the sql:
INFO: 2018-08-21 10:30:34,925:DartDBConnect.py:128: SELECT retry_logs from darttest WHERE id=1526706;
INFO: 2018-08-21 10:30:34,926:DartDBConnect.py:132: Select Return Value ========
INFO: 2018-08-21 10:30:34,926:DartDBConnect.py:133: [(None,)]
INFO: 2018-08-21 10:30:34,926:DartRunner.py:2629: Select Success: (None,) test NullTest
INFO: 2018-08-21 10:30:34,927:DartRunner.py:2630: [(None,)]
INFO: 2018-08-21 10:30:34,927:DartRunner.py:2332: RETRY LOG STRING =====
INFO: 2018-08-21 10:30:34,927:DartRunner.py:2333: None
INFO: 2018-08-21 10:30:34,938:DartRunner.py:2587: Updated Status: On test NullTest
INFO: 2018-08-21 10:30:34,938:DartRunner.py:2588: {'status': 'FAIL', 'execution_time': '00:00:00', 'log_location': u'/root/DartLogs/dart-main-sls12-05_NullTest_2018-08-21-103033.log', 'retry_count': 0, 'end_time': '2018-08-21 10:30:34', 'retry_logs': u'/root/DartLogs/dart-main-sls12-05_NullTest_2018-08-21-103033.log'}
INFO: 2018-08-21 10:30:34,938:DartRunner.py:2727: Attempting to get the Kernel and os information from the Cluster
ERROR: 2018-08-21 10:30:34,938:DartRunner.py:2918: Unable to run the command lsb_release -a
ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2919: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac06bdd0>)
ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2920: Traceback (most recent call last):
  File "DartRunner.py", line 2908, in runCommandOnQueen
    queenNode = queenNodes[0]
IndexError: list index out of range

ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2716: Can't get kernel or os information from cluster
ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2918: Unable to run the command cat /home/beehive/bin/.build | grep 'BUILD_VERSION'
ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2919: (<type 'exceptions.IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fc9ac045c20>)
ERROR: 2018-08-21 10:30:34,939:DartRunner.py:2920: Traceback (most recent call last):
  File "DartRunner.py", line 2908, in runCommandOnQueen
    queenNode = queenNodes[0]
IndexError: list index out of range

INFO: 2018-08-21 10:30:34,953:DartRunner.py:2587: Updated Status: On test NullTest
INFO: 2018-08-21 10:30:34,953:DartRunner.py:2588: {'revision': '08.00.00.00.0e93aa1b'}
INFO: 2018-08-21 10:30:42,950:DartRunner.py:1134: Done with initiating all the tests!
INFO: 2018-08-21 10:30:42,950:DartRunner.py:1209: Some tests are still running! Waiting for 10 seconds!
INFO: 2018-08-21 10:30:52,960:DartRunner.py:1213: Return Value:
INFO: 2018-08-21 10:30:52,961:DartRunner.py:2958:        SqlTests       NullTest     False         0 2018-08-21 10:30:33 2018-08-21 10:30:34
INFO: 2018-08-21 10:30:52,961:DartRunner.py:1647: -------------------------------------------------------------------------------------------------
INFO: 2018-08-21 10:30:52,961:DartRunner.py:1648: returnValue = {'test': OrderedDict([(u'NAME', u'NullTest'), (u'TYPE', u'SQL'), (u'QUERY', u'testsrc/queen/sql/test_sql/input/null.sql'), (u'EXPECTEDOUT', u'testsrc/queen/sql/test_sql/expectedQueryResults/null.out'), (u'TIMEOUT', 800), (u'PRIORITY', u'2'), (u'TEMPLATE', u'True'), (u'OWNER', u'divya.sivanandan'), (u'CATEGORY', u'positive'), (u'COMPONENT', u'queen/sql/test_sql'), (u'USER', u'beehive'), (u'PASSWORD', u'beehive'), (u'DATABASE', u'beehive'), (u'ACTPARAMS', u'-a'), ('runId', u'180821-38'), ('testSet', u'SqlTests'), ('testId', 1), ('timeScale', 1), ('projectName', 'MLEngine'), ('testPlan', None), ('buildName', 'beehive-ci-pipeline-main'), ('buildNumber', ''), ('tester', 'root'), ('release', 'GGR3'), ('branchName', '8.00engine.ggr3'), ('reTryCnt', 0), ('id', 1526706)]), 'clusterName': 'dartexe', 'totalTime': 1, 'testName': u'NullTest', 'testResults': OrderedDict([(u'SqlTests', [[u'NullTest', 0, False, '2018-08-21 10:30:33', '2018-08-21 10:30:34', u'/root/Dart/log/queen/sql/test_sql/dart-main-sls12-05_NullTest_2018-08-21-103033.log', u'dart-main-sls12-05_NullTest_2018-08-21-103033.log']])])}
INFO: 2018-08-21 10:30:52,961:DartRunner.py:1649: -------------------------------------------------------------------------------------------------
INFO: 2018-08-21 10:30:52,961:DartRunner.py:1219: Thread Count Went Down 0 
INFO: 2018-08-21 10:30:52,961:DartRunner.py:1237: The test NullTest returned back with the following result: False
INFO: 2018-08-21 10:30:53,190:DartRunner.py:2154: Ping on cluster dartexe Successful!
INFO: 2018-08-21 10:30:53,304:DartRunner.py:1260: Freeing up the cluster dartexe
INFO: 2018-08-21 10:30:53,304:DartRunner.py:1207: All the tests have been executed!
INFO: 2018-08-21 10:30:53,329:DartRunner.py:1309: {'dartexe': 'free'}
ERROR: 2018-08-21 10:30:53,332:DartRunner.py:1643: Send email fail: /bin/sh: 14: mail: not found
sh: echo: I/O error

INFO: 2018-08-21 10:30:53,665:DartRunner.py:2962: DartRunner Final Results!
INFO: 2018-08-21 10:30:53,666:DartRunner.py:2963:         TESTSET       TESTNAME    STATUS TOTALTIME           STARTTIME             ENDTIME
INFO: 2018-08-21 10:30:53,666:DartRunner.py:2958:        SqlTests       NullTest     False         0 2018-08-21 10:30:33 2018-08-21 10:30:34
INFO: 2018-08-21 10:30:53,666:DartRunner.py:2968: Dart DashBoard URL: http://dartdashboard.labs.teradata.com/report?run_id=180821-38
INFO: 2018-08-21 10:30:53,666:DartRunner.py:1347: Dart DashBoard URL: http://dartdashboard.labs.teradata.com/report?run_id=180821-38
